os: linux
dist: bionic
language: c

services:
  - docker

addons:
 snaps:
   - name: aws-cli
     confinement: classic

script:
  - make --no-builtin-rules build
  - make --no-builtin-rules test

deploy:
  provider: script
  skip_cleanup: true
  script:
    # Needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables
    - make --no-builtin-rules publish
  on:
    branch: master
